package com.saathi.focuscompanion.util

val funFacts = listOf(
    "Shampoo ka invention India mein hua tha!",
    "Zero ki khoj Brahmagupta ne ki thi.",
    "India mein duniya ka sabse bada postal network hai.",
    "Chess (Shatranj) ki khoj India mein hui thi!",
    "Takshashila duniya ki pehli university thi.",
    "Pi ka value Budhayana ne sabse pehle calculate kiya tha.",
    "Yoga 5,000 saal pehle India mein shuru hua.",
    "India mein 22 officially recognized languages hain.",
    "Kumbh Mela space se bhi dikhai deta hai!",
    "Plastic surgery ka concept India se aaya — Sushruta Samhita.",
    "India duniya ka sabse bada milk producer hai.",
    "Buttons ka invention Mohenjo-daro mein hua tha.",
    "Diamonds sabse pehle India mein mine kiye gaye the.",
    "Snakes and Ladders India mein bana tha — Moksha Patam!",
    "India ka first rocket cycle pe le jaaya gaya tha.",
    "Chand pe paani India ne (Chandrayaan-1) discover kiya.",
    "Aryabhata ne bataya tha ki Prithvi gol hai — 1500 saal pehle!",
    "India mein har saal almost 25,000 murders hote hain... mosquitoes ke!",
    "Indian Railways duniya ke sabse bade employers mein se hai.",
    "Varanasi duniya ka sabse purana continuously inhabited city hai.",
    "USB ka invention Ajay Bhatt ne kiya tha — an Indian!",
    "Pentium chip Intel ka — Vinod Dham ne design kiya, an Indian.",
    "Hotmail bhi ek Indian ne banaya — Sabeer Bhatia!",
    "India mein 300,000+ mosques hain — sabse zyada kisi bhi desh mein.",
    "Meghalaya mein duniya ki sabse zyada baarish hoti hai.",
    "India ka pehla satellite ka naam Aryabhata tha.",
    "ISRO ne ek hi rocket se 104 satellites launch kiye the.",
    "Martial art Kalaripayattu Kerala se hai — duniya ka sabse purana.",
    "Ramanujan ne bina formal training ke mathematics mein krantikari kaam kiya.",
    "APJ Abdul Kalam newspaper bechte the bachpan mein.",
    "Chanakya ko duniya ka pehla economist maana jaata hai.",
    "India duniya ka doosra sabse bada English-speaking country hai.",
    "Bangalore ko 'Silicon Valley of India' kehte hain.",
    "India mein 1,000+ engineering colleges hain.",
    "IIT Bombay 1958 mein UNESCO ki madad se bana tha.",
    "Har saal India se 1.5 million engineers graduate hote hain.",
    "Indian brain mein dum hai — Sundar Pichai, Satya Nadella!",
    "Mangalyaan mission Hollywood movie 'The Martian' se sasta tha!",
    "Lotus (kamal) India ka national flower hai.",
    "Bengal Tiger India ka national animal hai.",
    "India ka national game officially declared nahi hai!",
    "Taj Mahal ko banane mein 22 saal lage the.",
    "Indian cuisine mein 30+ variety ke rotis hain.",
    "Turmeric (haldi) ka use India mein 4,000 saal se ho raha hai.",
    "Jaipur ko 'Pink City' isliye kehte hain kyunki Prince Albert ke welcome mein pink paint kiya tha.",
    "Lucknow ki Biryani puri duniya mein famous hai.",
    "Ganges (Ganga) nadi ko 'Maa' kehte hain India mein.",
    "India mein duniya ke sabse zyada vegetarians hain.",
    "Banaras Hindu University Asia ka sabse bada residential university hai.",
    "Chai India mein 1830s ke baad popular hua — British ki wajah se!"
)
